DROP TABLE USERS;
DROP TABLE FRIENDS;
DROP TABLE MESSAGES;
DROP SEQUENCE USER_ID;
DROP SEQUENCE FRIENDS_ID;
DROP SEQUENCE MESSAGE_ID;
CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    UNIQUE(USERNAME),
    PASSWORD VARCHAR(100) NOT NULL
);

CREATE TABLE FRIENDS (
    ID INTEGER PRIMARY KEY,
    ID_USER1 INTEGER NOT NULL,
    ID_USER2 INTEGER NOT NULL
);

CREATE TABLE MESSAGES (
    ID INTEGER PRIMARY KEY,
    FROM_ID INTEGER NOT NULL,
    TO_ID INTEGER NOT NULL,
    MESSAGE VARCHAR(300) NOT NULL,
    TYPE INTEGER NOT NULL
);

CREATE SEQUENCE USER_ID
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

CREATE SEQUENCE FRIENDS_ID
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

CREATE SEQUENCE MESSAGE_ID
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;